mongodb:
  host: localhost
  port: 27017
  db: klight-api-gateway
  connection_pool_size: 1

openid:
  discovery_url: "http://127.0.0.1:8084/realms/klight-api-gateway/.well-known/openid-configuration"
  validate_scope: false
  flow_type: introspection
  introspection_endpoint: "http://127.0.0.1:8084/realms/klight-api-gateway/protocol/openid-connect/token/introspect"