mongodb:
  host: localhost
  port: 27017
  db: klight-api-gateway
  username: klight-api-gateway
  password: klight-api-gateway
  connection_pool_size: 1

openid:
  discovery_url: "http://127.0.0.1:8084/realms/klight-api-gateway/.well-known/openid-configuration"
  client_id: klight-api-gateway-openid-connect-authorize-code
  client_secret: iO2tmN0XvGfG7RpbANewVB78ZTZMPylP
  flow_type: authorization_code
  validate_scope: true
  scope: "openid email profile"
  redirect_uri: "/klight-api-gateway/auth/callback"
  redirect_uri_scheme: http