mongodb:
  username: klight-api-gateway
  password: klight-api-gateway

openid:
  client_id: klight-api-gateway-openid-connect-authorize-code
  client_secret: HWacRdRrMnUV2PY8Fy9v6x7WlR9W2TwA
  session_secret: "jjjjOjjl*nnnPPPPP767"

redis:
  username: klight-redis-user
  password: klight-redis-pass