mongodb:
  username: klight-api-gateway
  password: klight-api-gateway

openid:
  client_id: klight-api-gateway-openid-connect-authorize-code
  client_secret: Nf60zwcIYPZq509d4FnMTKeWtNMvQkL7
  session_secret: "jjjjOjjl*nnnPPPPP767"

redis:
  username: klight-redis-user
  password: klight-redis-pass